version: '3'

services:
    # Nginx Service
    nginx:
        image: nginx
        container_name: ${APP_NAME}_nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
            - ./.docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - postgres
    # PHP Service
    php:
        container_name: app_php
        build:
            context: .
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        depends_on:
            - postgres
    # PostgreSQL Service       
    postgres:
        image: postgres:16.0
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_HOST_AUTH_METHOD: "trust"
