version: '3'

services:
    nginx:
        image: nginx
        container_name: ${APP_NAME}_nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
            - ./.docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - postgres
    # PHP Service
    php:
        build:
            context: .
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        user: "1000:1000"
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        depends_on:
            - postgres
    postgres:
        image: postgres:16.0
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5433:5432"
        volumes:
            - ./.docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
